import React, { useState, useImperativeHandle, forwardRef, useEffect } from 'react';
import { Box, Typography, TextField, MenuItem, Snackbar, Alert, Dialog, DialogTitle, DialogContent, DialogActions, Button } from '@mui/material';
import { infoCollApi } from '../../services/api';

const genderOptions = ['Male', 'Female', 'Other'];
const visaOptions = ['Visa Abroad', 'Adjust Status'];

interface FormErrors {
  [key: string]: boolean;
}

const InfoCollSpouseInfo = forwardRef(({ clientCaseId, userId }: { clientCaseId: number, userId: string }, ref) => {
  const [formData, setFormData] = useState<{ [key: string]: any }>({});
  const [errors, setErrors] = useState<FormErrors>({});
  const [snackbar, setSnackbar] = useState<{ open: boolean; message: string; severity: 'success' | 'error' }>({ open: false, message: '', severity: 'success' });
  const [validationDialog, setValidationDialog] = useState<{ open: boolean; message: string }>({ open: false, message: '' });

  useEffect(() => {
    if (clientCaseId) {
      infoCollApi.getSpouseInfo(clientCaseId).then(res => {
        if (res && res.data) {
          setFormData(res.data);
        }
      }).catch(() => {
        // 可以加错误提示
      });
    }
  }, [clientCaseId]);

  // 通用输入处理
  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
    const { name, value } = e.target;
    setFormData(prev => ({ ...prev, [name]: value }));
    // 清除该字段的错误状态
    setErrors(prev => ({ ...prev, [name]: false }));
  };

  // 下拉选择处理
  const handleSelectChange = (name: string) => (e: any) => {
    setFormData(prev => ({ ...prev, [name]: e.target.value }));
    // 清除该字段的错误状态
    setErrors(prev => ({ ...prev, [name]: false }));
  };

  // 关闭snackbar
  const handleCloseSnackbar = () => {
    setSnackbar(prev => ({ ...prev, open: false }));
  };

  // 验证表单
  const validateForm = (): boolean => {
    const newErrors: FormErrors = {};
    let isValid = true;

    // 必填字段验证
    const requiredFields = [
      'firstName',
      'lastName',
      'gender',
      'dob',
      'visaStatus'
    ];

    requiredFields.forEach(field => {
      if (!formData[field]) {
        newErrors[field] = true;
        isValid = false;
      }
    });

    setErrors(newErrors);

    if (!isValid) {
      setValidationDialog({
        open: true,
        message: 'Please fill in all required fields.'
      });
    }

    return isValid;
  };

  // 暴露方法给父组件
  useImperativeHandle(ref, () => ({
    getFormData: () => formData,
    submit: async (clientCase: any) => {
      if (!validateForm()) {
        return;
      }

      try {
        const data = { ...formData, clientCaseId: clientCase.clientCaseId };
        await infoCollApi.submitSpouseInfo(data);
        setSnackbar({ open: true, message: 'Successfully saved', severity: 'success' });
      } catch (e: any) {
        setSnackbar({ open: true, message: e?.message || 'Save failed', severity: 'error' });
      }
    }
  }));

  return (
    <Box component="form" noValidate autoComplete="off">
      <Alert severity="warning" sx={{ mb: 2 }}>
        Reminder: If you do not click Save, your changes will be lost.
      </Alert>
      <Typography variant="h6" fontWeight={700} sx={{ mb: 2 }}>Spouse Info</Typography>
      
      {/* Respondents (autogenerated) */}
      <TextField 
        label="Respondents (autogenerated)" 
        fullWidth 
        size="small" 
        sx={{ mb: 2 }} 
        InputProps={{ readOnly: true }} 
        value={userId} 
      />
      
      {/* First Name (Spouse) */}
      <TextField
        name="firstName"
        label="First Name (Spouse)"
        fullWidth
        size="small"
        sx={{ mb: 2 }}
        value={formData.firstName || ''}
        onChange={handleChange}
        required
        error={errors.firstName}
        helperText={errors.firstName ? 'First Name is required' : ''}
      />

      {/* Middle Name (Spouse) */}
      <TextField
        name="middleName"
        label="Middle Name (Spouse)"
        fullWidth
        size="small"
        sx={{ mb: 2 }}
        value={formData.middleName || ''}
        onChange={handleChange}
      />

      {/* Last Name (Spouse) */}
      <TextField
        name="lastName"
        label="Last Name (Spouse)"
        fullWidth
        size="small"
        sx={{ mb: 2 }}
        value={formData.lastName || ''}
        onChange={handleChange}
        required
        error={errors.lastName}
        helperText={errors.lastName ? 'Last Name is required' : ''}
      />

      {/* Gender (Spouse) */}
      <TextField
        name="gender"
        label="Gender (Spouse)"
        select
        fullWidth
        size="small"
        sx={{ mb: 2 }}
        value={formData.gender || ''}
        onChange={handleSelectChange('gender')}
        required
        error={errors.gender}
        helperText={errors.gender ? 'Gender is required' : ''}
      >
        {genderOptions.map(opt => <MenuItem key={opt} value={opt}>{opt}</MenuItem>)}
      </TextField>

      {/* Date of Birth (Spouse) */}
      <TextField
        name="dob"
        label="Date of Birth (Spouse)"
        type="date"
        fullWidth
        size="small"
        sx={{ mb: 2 }}
        InputLabelProps={{ shrink: true }}
        value={formData.dob || ''}
        onChange={handleChange}
        required
        error={errors.dob}
        helperText={errors.dob ? 'Date of Birth is required' : ''}
      />

      {/* Visa Status */}
      <TextField
        name="visaStatus"
        label="Will he/she apply for a visa abroad or adjust status in the US?"
        select
        fullWidth
        size="small"
        sx={{ mb: 2 }}
        value={formData.visaStatus || ''}
        onChange={handleSelectChange('visaStatus')}
        required
        error={errors.visaStatus}
        helperText={errors.visaStatus ? 'Visa Status is required' : ''}
      >
        {visaOptions.map(opt => <MenuItem key={opt} value={opt}>{opt}</MenuItem>)}
      </TextField>

      <Snackbar
        open={snackbar.open}
        autoHideDuration={4000}
        onClose={handleCloseSnackbar}
        anchorOrigin={{ vertical: 'top', horizontal: 'center' }}
      >
        <Alert onClose={handleCloseSnackbar} severity={snackbar.severity} sx={{ width: '100%' }}>
          {snackbar.message}
        </Alert>
      </Snackbar>

      <Dialog
        open={validationDialog.open}
        onClose={() => setValidationDialog({ open: false, message: '' })}
      >
        <DialogTitle>Validation Error</DialogTitle>
        <DialogContent>
          <Typography>{validationDialog.message}</Typography>
        </DialogContent>
        <DialogActions>
          <Button onClick={() => setValidationDialog({ open: false, message: '' })}>
            OK
          </Button>
        </DialogActions>
      </Dialog>
    </Box>
  );
});

export default InfoCollSpouseInfo; 