import React, { useState, useImperativeHandle, forwardRef, useEffect } from 'react';
import { Box, Typography, TextField, MenuItem, Snackbar, Alert, Dialog, DialogTitle, DialogContent, DialogActions, Button } from '@mui/material';
import FileUploadButton from '../../components/FileUploadButton';
import { infoCollApi } from '../../services/api';
import { extractFileName } from '../../services/s3Service';
import { countryOptions } from '../../constants/countries';
import InfoCollAlert from '../../components/InfoCollAlert';
// import { LocalizationProvider } from '@mui/x-date-pickers/LocalizationProvider';
// import { AdapterDateFns } from '@mui/x-date-pickers/AdapterDateFns';
// import { enUS, zhCN } from 'date-fns/locale'; // Import the English (US) locale

const genderOptions = ['Male', 'Female', 'Other'];
const yesNoOptions = ['Yes', 'No'];
const visaOptions = ['Visa Abroad', 'Adjust Status'];

interface FormErrors {
  [key: string]: boolean;
}

const InfoCollBasicInfo = forwardRef(({ clientCaseId, userId, userType }: { clientCaseId: number, userId: string, userType: string }, ref) => {
  const [formData, setFormData] = useState<{ [key: string]: any }>({});
  const [errors, setErrors] = useState<FormErrors>({});
  const [snackbar, setSnackbar] = useState<{ open: boolean; message: string; severity: 'success' | 'error' }>({ open: false, message: '', severity: 'success' });
  const [validationDialog, setValidationDialog] = useState<{ open: boolean; message: string }>({ open: false, message: '' });

  useEffect(() => {
    if (clientCaseId) {
      infoCollApi.getBasicInfo(clientCaseId).then(res => {
        if (res && res.data) {
          setFormData(res.data);
        }
      }).catch(() => {
        // 可以加错误提示
      });
    }
  }, [clientCaseId]);

  // 通用输入处理
  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
    const { name, value } = e.target;
    const newFormData = { ...formData, [name]: value };
    
    // 如果修改的是名字相关字段，自动更新fullName
    if (['firstName', 'middleName', 'lastName'].includes(name)) {
      const fullName = [
        newFormData.firstName,
        newFormData.middleName,
        newFormData.lastName
      ].filter(Boolean).join(' ');
      newFormData.fullName = fullName;
    }
    
    setFormData(newFormData);
    // 清除该字段的错误状态
    setErrors(prev => ({ ...prev, [name]: false }));
  };

  // 下拉选择处理
  const handleSelectChange = (name: string) => (e: any) => {
    setFormData(prev => ({ ...prev, [name]: e.target.value }));
    // 清除该字段的错误状态
    setErrors(prev => ({ ...prev, [name]: false }));
  };

  // 上传文件回调
  const handleFileUrlChange = (name: string, url: string | null) => {
    setFormData(prev => ({ ...prev, [name]: url }));
    // 清除该字段的错误状态
    setErrors(prev => ({ ...prev, [name]: false }));
  };

  // 关闭snackbar
  const handleCloseSnackbar = () => {
    setSnackbar(prev => ({ ...prev, open: false }));
  };

  // 验证表单
  const validateForm = (): boolean => {
    const newErrors: FormErrors = {};
    let isValid = true;

    // 必填字段验证
    const requiredFields = [
      'firstName',
      'lastName',
      'email',
      'gender',
      'premiumProcessing',
      'phoneNumber',
      'dob',
      'ssn',
      'birthLocation',
      'citizenship',
      'usAddress',
      'foreignAddressNative',
      'foreignAddressEng',
      'residenceCountry',
      'visaStatus',
      'kidsCount',
      'immigrationPetition',
      'maritalStatus'
    ];

    requiredFields.forEach(field => {
      if (!formData[field]) {
        newErrors[field] = true;
        isValid = false;
      }
    });

    // 文件上传验证
    if (!formData.passport) {
      newErrors.passport = true;
      isValid = false;
    }
    if (!formData.i94) {
      newErrors.i94 = true;
      isValid = false;
    }
    if (formData.immigrationPetition === 'Yes' && !formData.petitionNotice) {
      newErrors.petitionNotice = true;
      isValid = false;
    }

    setErrors(newErrors);

    if (!isValid) {
      setValidationDialog({
        open: true,
        message: 'Please fill in all required fields and upload required documents.'
      });
    }

    return isValid;
  };

  // 暴露方法给父组件
  useImperativeHandle(ref, () => ({
    getFormData: () => formData,
    submit: async (clientCase: any) => {
      if (!validateForm()) {
        return;
      }

      try {
        const data = { ...formData, clientCaseId: clientCase.clientCaseId };
        await infoCollApi.submitBasicInfo(data);
        setSnackbar({ open: true, message: 'Successfully saved', severity: 'success' });
      } catch (e: any) {
        setSnackbar({ open: true, message: e?.message || 'Save failed', severity: 'error' });
      }
    }
  }));

  return (
    <Box component="form" noValidate autoComplete="off">
      <InfoCollAlert userType={userType} />
      <Typography variant="h6" fontWeight={700} sx={{ mb: 2 }}>Basic Info</Typography>
      
      {/* Respondents (autogenerated) */}
      <TextField 
        label="Respondents (autogenerated)" 
        fullWidth 
        size="small" 
        sx={{ mb: 2 }} 
        InputProps={{ readOnly: true }} 
        value={userId} 
      />

      {/* First Name */}
      <TextField
        name="firstName"
        label="First Name"
        fullWidth
        size="small"
        sx={{ mb: 2 }}
        value={formData.firstName || ''}
        onChange={handleChange}
        required
        error={errors.firstName}
        helperText={errors.firstName ? 'First Name is required' : ''}
      />

      {/* Middle Name */}
      <TextField
        name="middleName"
        label="Middle Name (optional)"
        fullWidth
        size="small"
        sx={{ mb: 2 }}
        value={formData.middleName || ''}
        onChange={handleChange}
      />

      {/* Last Name */}
      <TextField
        name="lastName"
        label="Last Name"
        fullWidth
        size="small"
        sx={{ mb: 2 }}
        value={formData.lastName || ''}
        onChange={handleChange}
        required
        error={errors.lastName}
        helperText={errors.lastName ? 'Last Name is required' : ''}
      />

      {/* Full Name (autogenerated) */}
      <TextField
        name="fullName"
        label="Full Name (autogenerated)"
        fullWidth
        size="small"
        sx={{ mb: 2 }}
        InputProps={{ readOnly: true }}
        value={
          (formData.firstName || '') +
          (formData.middleName ? ' ' + formData.middleName : '') +
          (formData.lastName ? ' ' + formData.lastName : '') || 'Auto generated'
        }
      />

      {/* Email */}
      <TextField
        name="email"
        label="Email"
        type="email"
        fullWidth
        size="small"
        sx={{ mb: 2 }}
        value={formData.email || ''}
        onChange={handleChange}
        required
        error={errors.email}
        helperText={errors.email ? 'Email is required' : ''}
      />

      {/* Gender */}
      <TextField
        name="gender"
        label="Gender"
        select
        fullWidth
        size="small"
        sx={{ mb: 2 }}
        value={formData.gender || ''}
        onChange={handleSelectChange('gender')}
        required
        error={errors.gender}
        helperText={errors.gender ? 'Gender is required' : ''}
      >
        {genderOptions.map(opt => <MenuItem key={opt} value={opt}>{opt}</MenuItem>)}
      </TextField>

      {/* Premium Processing */}
      <TextField
        name="premiumProcessing"
        label="Do you want premium processing?"
        select
        fullWidth
        size="small"
        sx={{ mb: 2 }}
        value={formData.premiumProcessing || ''}
        onChange={handleSelectChange('premiumProcessing')}
        required
        error={errors.premiumProcessing}
        helperText={errors.premiumProcessing ? 'Premium processing choice is required' : ''}
      >
        {yesNoOptions.map(opt => <MenuItem key={opt} value={opt}>{opt}</MenuItem>)}
      </TextField>

      {/* Phone Number */}
      <TextField
        name="phoneNumber"
        label="Phone Number"
        fullWidth
        size="small"
        sx={{ mb: 2 }}
        value={formData.phoneNumber || ''}
        onChange={handleChange}
        required
        error={errors.phoneNumber}
        helperText={errors.phoneNumber ? 'Phone Number is required' : ''}
      />

      {/* Date of Birth */}
      <TextField
        name="dob"
        label="Date of Birth"
        type="date"
        fullWidth
        size="small"
        sx={{ mb: 2 }}
        InputLabelProps={{ shrink: true }}
        value={formData.dob || ''}
        onChange={handleChange}
        required
        error={errors.dob}
        helperText={errors.dob ? 'Date of Birth is required' : ''}
      />
      

      {/* SSN */}
      <TextField
        name="ssn"
        label="SSN"
        fullWidth
        size="small"
        sx={{ mb: 2 }}
        value={formData.ssn || ''}
        onChange={handleChange}
        required
        error={errors.ssn}
        helperText={errors.ssn ? 'SSN is required' : ''}
      />

      {/* City/Province/Country of Birth */}
      <TextField
        name="birthLocation"
        label="City/Province/Country of Birth"
        fullWidth
        size="small"
        sx={{ mb: 2 }}
        value={formData.birthLocation || ''}
        onChange={handleChange}
        required
        error={errors.birthLocation}
        helperText={errors.birthLocation ? 'Birth Location is required' : ''}
      />

      {/* Country of Citizenship */}
      <TextField
        name="citizenship"
        label="Country of Citizenship"
        select
        fullWidth
        size="small"
        sx={{ mb: 2 }}
        value={formData.citizenship || ''}
        onChange={handleSelectChange('citizenship')}
        required
        error={errors.citizenship}
        helperText={errors.citizenship ? 'Country of Citizenship is required' : ''}
      >
        {countryOptions.map((opt: string) => <MenuItem key={opt} value={opt}>{opt}</MenuItem>)}
      </TextField>

      {/* Current US Address */}
      <TextField
        name="usAddress"
        label="Current US Address"
        fullWidth
        size="small"
        sx={{ mb: 2 }}
        value={formData.usAddress || ''}
        onChange={handleChange}
        required
        error={errors.usAddress}
        helperText={errors.usAddress ? 'US Address is required' : ''}
      />

      {/* Foreign Address (Native Language) */}
      <TextField
        name="foreignAddressNative"
        label="Foreign Address (Native Language)"
        fullWidth
        size="small"
        sx={{ mb: 2 }}
        value={formData.foreignAddressNative || ''}
        onChange={handleChange}
        required
        error={errors.foreignAddressNative}
        helperText={errors.foreignAddressNative ? 'Foreign Address in Native Language is required' : ''}
      />

      {/* Foreign Address (English) */}
      <TextField
        name="foreignAddressEng"
        label="Foreign Address (English)"
        fullWidth
        size="small"
        sx={{ mb: 2 }}
        value={formData.foreignAddressEng || ''}
        onChange={handleChange}
        required
        error={errors.foreignAddressEng}
        helperText={errors.foreignAddressEng ? 'Foreign Address in English is required' : ''}
      />

      {/* Current Country of Residence */}
      <TextField
        name="residenceCountry"
        label="Current Country of Residence"
        fullWidth
        size="small"
        sx={{ mb: 2 }}
        value={formData.residenceCountry || ''}
        onChange={handleChange}
        required
        error={errors.residenceCountry}
        helperText={errors.residenceCountry ? 'Country of Residence is required' : ''}
      />

      {/* Will you apply for a visa abroad or adjust in the US? */}
      <TextField
        name="visaStatus"
        label="Will you apply for a visa abroad or adjust in the US?"
        select
        fullWidth
        size="small"
        sx={{ mb: 2 }}
        value={formData.visaStatus || ''}
        onChange={handleSelectChange('visaStatus')}
        required
        error={errors.visaStatus}
        helperText={errors.visaStatus ? 'Visa Status is required' : ''}
      >
        {visaOptions.map(opt => <MenuItem key={opt} value={opt}>{opt}</MenuItem>)}
      </TextField>

      {/* How many kids do you have? */}
      <TextField
        name="kidsCount"
        label="How many kids do you have?"
        fullWidth
        size="small"
        sx={{ mb: 2 }}
        value={formData.kidsCount || ''}
        onChange={handleChange}
        type="number"
        required
        error={errors.kidsCount}
        helperText={errors.kidsCount ? 'Number of kids is required' : ''}
      />

      {/* Has any immigration petition been filed on your behalf? */}
      <TextField
        name="immigrationPetition"
        label="Has any immigration petition been filed on your behalf?"
        select
        fullWidth
        size="small"
        sx={{ mb: 2 }}
        value={formData.immigrationPetition || ''}
        onChange={handleSelectChange('immigrationPetition')}
        required
        error={errors.immigrationPetition}
        helperText={errors.immigrationPetition ? 'Immigration Petition status is required' : ''}
      >
        {yesNoOptions.map(opt => <MenuItem key={opt} value={opt}>{opt}</MenuItem>)}
      </TextField>

      {/* If yes, upload receipt/approval notice */}
      {formData.immigrationPetition === 'Yes' && (
        <FileUploadButton
          label="Upload Receipt/Approval Notice (PDF)"
          fileType="petitionNotice"
          onFileUrlChange={url => handleFileUrlChange('petitionNotice', url)}
          required
          error={errors.petitionNotice}
          fileUrl={formData.petitionNotice}
          fileName={formData.petitionNotice && extractFileName(formData.petitionNotice)}
        />
      )}

      {/* Copy of Passport */}
      <FileUploadButton
        label="Upload Copy of Passport (PDF)"
        fileType="passport"
        onFileUrlChange={url => handleFileUrlChange('passport', url)}
        required
        fileUrl={formData.passport}
        fileName={formData.passport && extractFileName(formData.passport)}
        error={errors.passport}
      />

      {/* Copy of Old Passport (optional) */}
      <FileUploadButton
        label="Upload Copy of Old Passport (PDF, optional)"
        fileType="oldPassport"
        onFileUrlChange={url => handleFileUrlChange('oldPassport', url)}
        fileUrl={formData.oldPassport}
        fileName={formData.oldPassport && extractFileName(formData.oldPassport)}
      />

      {/* Copy of Visa Stamp (optional) */}
      <FileUploadButton
        label="Upload Copy of Visa Stamp (PDF, optional)"
        fileType="visaStamp"
        onFileUrlChange={url => handleFileUrlChange('visaStamp', url)}
        fileUrl={formData.visaStamp}
        fileName={formData.visaStamp && extractFileName(formData.visaStamp)}
      />

      {/* Copy of Most Recent I-94 */}
      <FileUploadButton
        label="Upload Copy of Most Recent I-94 (PDF)"
        fileType="i94"
        onFileUrlChange={url => handleFileUrlChange('i94', url)}
        required
        error={errors.i94}
        fileUrl={formData.i94}
        fileName={formData.i94 && extractFileName(formData.i94)}
      />

      {/* Copy of Non-Immigrant Status Evidence (optional) */}
      <FileUploadButton
        label="Upload Copy of Non-Immigrant Status Evidence (PDF, optional)"
        fileType="nonimmigrantStatus"
        onFileUrlChange={url => handleFileUrlChange('nonimmigrantStatus', url)}
        fileUrl={formData.nonimmigrantStatus}
        fileName={formData.nonimmigrantStatus && extractFileName(formData.nonimmigrantStatus)}
      />

      {/* Are you single? */}
      <TextField
        name="maritalStatus"
        label="Are you single?"
        select
        fullWidth
        size="small"
        sx={{ mb: 2 }}
        value={formData.maritalStatus || ''}
        onChange={handleSelectChange('maritalStatus')}
        required
        error={errors.maritalStatus}
        helperText={errors.maritalStatus ? 'Marital Status is required' : ''}
      >
        {yesNoOptions.map(opt => <MenuItem key={opt} value={opt}>{opt}</MenuItem>)}
      </TextField>

      <Snackbar
        open={snackbar.open}
        autoHideDuration={4000}
        onClose={handleCloseSnackbar}
        anchorOrigin={{ vertical: 'top', horizontal: 'center' }}
      >
        <Alert onClose={handleCloseSnackbar} severity={snackbar.severity} sx={{ width: '100%' }}>
          {snackbar.message}
        </Alert>
      </Snackbar>

      <Dialog
        open={validationDialog.open}
        onClose={() => setValidationDialog({ open: false, message: '' })}
      >
        <DialogTitle>Validation Error</DialogTitle>
        <DialogContent>
          <Typography>{validationDialog.message}</Typography>
        </DialogContent>
        <DialogActions>
          <Button onClick={() => setValidationDialog({ open: false, message: '' })}>
            OK
          </Button>
        </DialogActions>
      </Dialog>
    </Box>
  );
});

export default InfoCollBasicInfo; 